server:
  port: 8010
kafka:
  bootstrap-servers: localhost:9092
  
spring:
  cloud:
    stream:
      bindings:
        device_data:
            destination: devicetopic
        heg_topic:
            consumer: 
              header-mode: raw 
eureka:
  client:
    enabled: false
